### ISSUE TITLE
action after entering parens group gives parse error

### ISSUE THREAD

**Issue by rofl0r** [adrian-thurston/ragel#53]
e.g. `main := ( >{puts("x");} (  [0-9]+ ) "foo");`

i'd like to have an action executed as soon as a parenthesized group is entered to mimic regexec() behaviour to put start and end offset of a matching group into an array.

is this just an oversight in the ragel parser? if not could someone provide a hint how i could achieve the desired behaviour? thanks in advance.

**Comment by adrian-thurston** [comment]
Hi @rofl0r go like this:

`main := ( "" >{puts("x");} ( [0-9]+ ) "foo" );`

**Comment by rofl0r** [comment]
oh thanks, nice trick. however i found a workaround as can be seen here https://sabotage-linux.github.io/blog/7/
