### ISSUE TITLE
ragel 7: -C is an invalid argument

### ISSUE THREAD

**Issue by evanmiller** [adrian-thurston/ragel#62]
I have some scripts written for Ragel 6 that use the `-C` argument. These exit with an error using Ragel 7 (" -C is an invalid argument"). The flag is advertised as valid in the `--help` output.

**Comment by adrian-thurston** [comment]
Thanks Evan, I removed the items from the help screen. While ragel 7 programs are compatible with version 6, but the command line is not. All the non-C languages are now distributed as separate binaries, so it doesn't make sense to support those old command line options anymore.
