### ISSUE TITLE
fatal error: gen/if1.h: No such file or directory, fatal error: colm/rtvector.h: No such file or directory

### ISSUE THREAD

**Issue by garyemiller** [adrian-thurston/ragel#63]
When I try to build the Gentoo colm 0.14.6 package I get errors.   Version 0.13.0.7 built fine.

When I build with  -j6, this happens:

```
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I.  -I../src/aapl  -Iinclude  -Wall -DPREFIX='"/usr"' -DLOAD_INIT -march=znver2 -O2 -pipe -c -o gen/bootstrap1-if1.o `test -f 'gen/if1.cc' || echo './'`gen/if1.cc
gen/if1.cc:1:10: fatal error: gen/if1.h: No such file or directory
    1 | #include "gen/if1.h"
      |          ^~~~~~~~~~~
compilation terminated.
```

When I build with -j1 this happens.:

```
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../src/aapl -Iinclude -march=znver2 -O2 -pipe -c codevect.c  -fPIC -DPIC -o .libs/codevect.o
codevect.c:26:10: fatal error: colm/rtvector.h: No such file or directory
   26 | #include <colm/rtvector.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Gentoo issue: https://bugs.gentoo.org/766327

**Comment by adrian-thurston** [comment]
Okay thanks, might be missing some dependencies.

**Comment by adrian-thurston** [comment]
Yeah I'm trying to use built sources in multiple levels of the dependency graph. One of the items in the built sources is built by a program that needs to be built itself, and it has built sources too. I just pushed a commit where the dependencies are more explicitly stated. Are you able to try that out in the ebuild. Want to avoid making a release that needs further corrections. Attached is a tarball.
[colm-0.14.6.tar.gz](https://github.com/adrian-thurston/ragel/files/5900724/colm-0.14.6.tar.gz)

**Comment by garyemiller** [comment]
I'm willing to try anything, but not sure exactly what I should do with the tarball.

**Comment by garyemiller** [comment]
The README says:

```
Colm is built in the usual autotool way:

$ ./autogen
$ ./configure
$ make
$ make install
```

But there is not file autogen.

I have not built this from source before, instead I used the Gentoo ebuild.

**Comment by thesamesam** [comment]
@garyemiller In a local overlay or the main repo, do the following (I've used the main repo as an example):

Go to /var/db/repos/gentoo/dev-util/colm and change the ebuild to have 
SRC_URI="https://github.com/adrian-thurston/ragel/files/5900724/colm-0.14.6.tar.gz"

then run 'repoman manifest' in that directory, then 'ebuild colm-0.14.6.ebuild clean merge' and tell us if it works.

**Comment by adrian-thurston** [comment]
Thanks @thesamesam, when it's correct I'll produce another release of colm and also ragel.

**Comment by garyemiller** [comment]
I tried that.  Results for "-j6"

```
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../src/aapl -Iinclude -march=znver2 -O2 -pipe -c codevect.c  -fPIC -DPIC -o .libs/codevect.o
codevect.c:26:10: fatal error: colm/rtvector.h: No such file or directory
   26 | #include <colm/rtvector.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:977: codevect.lo] Error 1
```

It did work with "-j1".  So still a problem with parallel builds.

**Comment by adrian-thurston** [comment]
Do we have builddir != srcdir in gentoo builds?

**Comment by garyemiller** [comment]
I'm not sure, but I think builddir == srcdir.  Build log attached.
[build.log](https://github.com/adrian-thurston/ragel/files/5936048/build.log)

**Comment by adrian-thurston** [comment]
Yeah can see from the log they are the same. There is a `./configure`.

**Comment by thesamesam** [comment]
Yeah, we gave up on out-of-source builds for autotools stuff (before my time). Give me a shout if I can do any more.

**Comment by adrian-thurston** [comment]
Got another tarball to try. Found another missing dependency after switching away from `BUILT_SOURCES`, which is insufficient in this case.
[colm-0.14.6.tar.gz](https://github.com/adrian-thurston/ragel/files/5937580/colm-0.14.6.tar.gz)

**Comment by adrian-thurston** [comment]
Gary is doing something right, because he is hitting the paths that expose the bugs.

**Comment by adrian-thurston** [comment]
I'm also going to try and make the build work with builddir != srcdir since it can help harden the build.

**Comment by garyemiller** [comment]
I just tried the new tar, same results with -j6.

Build log attached.

[build.log](https://github.com/adrian-thurston/ragel/files/5937617/build.log)

Why does doing something right feel so wrong?

I doubt it is a directory problem,  Feels to me like a dependency problem that parallel building break.

**Comment by adrian-thurston** [comment]
It definitely is, I'm not understanding the dependencies I have specified are working for me and not for you. I think I might just move the creation of that dir to configure. Or move the files into a real subdir so the `<colm/*>` includes work without needing anyunusual hacks.

**Comment by rofl0r** [comment]
should be pretty straightforward to figure out from the build log. in case of a couple comments above

> codevect.c:26:10: fatal error: colm/rtvector.h: No such file or directory

codevect.c didn't have the dependency on rtvector documented.

btw, there's also [remake](https://github.com/rocky/remake) which has some nifty debug options to show where dependencies come from (or not).

**Comment by adrian-thurston** [comment]
It's a dependency on a directory `include/colm`. I might be going outside of what is expected to work and be portable.

**Comment by adrian-thurston** [comment]
I noticed in the build log that there is an autoconf and automake step. Wondering why that's run. Isn't it normal to just run `./configure` when working with the distribution tarball?

**Comment by rofl0r** [comment]
> Isn't it normal to just run ./configure when working with the distribution tarball?

it is indeed. though if a part of the autoconf input files need to be patched, then you have to rerun autoreconf. also in the age of github-download-from-tag tarballs, many autoconf users don't even provide a proper release tarball with configure script anymore, so maybe it has become a habit for some package maintainers to automatically run autogen.sh, autoreconf, or whatever.

**Comment by adrian-thurston** [comment]
Capitulation: moved the steps I can't make happen for you into the configure script. Would prefer to understand the problem, but gotta move on for now :)

[colm-0.14.6.tar.gz](https://github.com/adrian-thurston/ragel/files/5939684/colm-0.14.6.tar.gz)

**Comment by rofl0r** [comment]
> It's a dependency on a directory include/colm

maybe it could be done with a "stamp file".

e.g:
```make
gen/stamp: gen/foo.h gen/rtvect.h
    touch gen/stamp

foo.c bar.c baz.c: gen/stamp
```

**Comment by adrian-thurston** [comment]
Hmm, yeah maybe it could be a stamp alongside the dir that is made and that would do it. I'm afraid to try at this point though. I think Gary needs a break too :)

**Comment by garyemiller** [comment]
Adrian, I have certainly not lost interest, I'll help what little I can, just not a high priority for me.

I just tried the tar ball above. https://github.com/adrian-thurston/ragel/issues/63#issuecomment-774723084 And that built fine with "-j6".  Ship it!

**Comment by adrian-thurston** [comment]
Oh great! Didn't mean to suggest you lost interest, just felt like I was wasting your time by sending over tarballs that keep having problems. But all good now, excellent!

**Comment by thesamesam** [comment]
Thanks a bunch guys. @adrian-thurston Are you shipping a new release or should I use the working tarball as a new revision?

**Comment by adrian-thurston** [comment]
@thesamesam I'll do a new release today. It's possible that ragel itself will have some of the same problems as I use similar techniques there.
