### ISSUE TITLE
Build failure "configure: error: colm is required to build ragel".  README out-of-date?

### ISSUE THREAD

**Issue by seanm** [adrian-thurston/ragel#79]
I'm reading the README, and trying to build for the first time (from git master), but I hit a few issues.

(1) it says:

```
Colm is built in the usual autotool way:

$ ./autogen
...
```

There is no such file though, but there is one named `autogen.sh`.  I guess that's what the README means?

(2) Assuming so, I got a bit further, but hit:

`configure: error: colm is required to build ragel`

This confuses me, because the README says "This package has no external dependencies, other than usual autotools and C/C++ compiler programs"

So I have a feeling the README is a bit out-of-date?

**Comment by adrian-thurston** [comment]
Thanks for reporting this Sean. The README should now be current.
